# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4319f873619c751834e550177757715b637f2276d08c635cf1e52c6eb181d5a354c396e5650eaaffdd9c33638934da56519d00a6258f2671d2550f31f7ed88eb

test:
  secret_key_base: 3442f9b5cc85f1276a5dfe7f4ee2c7f31e904917a60e6463fca50fbfaf08c56fba246f06ef1afe9c74eccee4eee7501b1fcff3ee6e46060fbf9a9cd577d08917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
